# Generated by Django 4.2.4 on 2023-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=None, upload_to='postimg'),
            preserve_default=False,
        ),
    ]
